name: Test Workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Install dependencies
        run: 
          yarn install
      - name: Run lint
        run: |
          cd functions
          yarn lint
      - name: Run tests
        run: |
          cd functions
          yarn test
