name: Test Workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: |
          cd functions
          yarn install
      - name: Run lint
        run: |
          cd functions
          yarn lint
      - name: Run tests
        run: |
          cd functions
          yarn test
